gestao_rh/apps/funcionario/urls.py
from .views import home
from django.urls import path
from .views import ListFuncionario, UpdateFuncionario, DeleteFuncionario, CreateFuncionario, CSVFuncionario, celery

from django.urls import include, path





urlpatterns = [
    path('', home),
    path('list/', ListFuncionario.as_view(), name="funcionario-lista"),
    path('update/<pk>', UpdateFuncionario.as_view(), name="funcionario-update"),
    path('delete/<pk>', DeleteFuncionario.as_view(), name="funcionario-delete"),
    path('create/', CreateFuncionario.as_view(), name="funcionario-create"),
    path('funcionario-csv/<pk>', CSVFuncionario.as_view(), name="funcionario-csv"),
    path('celery/', celery, name='celery')


]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers

from gestao_rh.apps.funcionario.api.views import FuncionarioViewSet
from gestao_rh.apps.registro_hora_extra.api.views import HoraExtraViewSet

router = routers.DefaultRouter()
router.register(r'funcionario', FuncionarioViewSet)
router.register(r'hora-extra', HoraExtraViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('funcionario/', include('gestao_rh.apps.funcionario.urls')),
    path('empresa/', include('gestao_rh.apps.empresa.urls')),
    path('departamento/', include('gestao_rh.apps.departamento.urls')),
    path('documento/', include('gestao_rh.apps.documento.urls')),
    path('hora-extra/', include('gestao_rh.apps.registro_hora_extra.urls')),
    path('', include('gestao_rh.apps.home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('pdf/', include('gestao_rh.apps.pdf.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestao_rh/apps/documento/models.py
from django.db import models
from ..funcionario.models import Funcionario


class Documento(models.Model):

    nome = models.CharField(max_length=120, help_text="Nome do documento")
    propriedade_de = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def __str__(self):
        return self.nome

gestao_rh/apps/funcionario/models.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse
from ..departamento.models import Departamento
from ..empresa.models import Empresa
from django.db.models import Sum


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Funcionario(models.Model):
    nome = models.CharField(max_length=100, help_text="Informe o nome")
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento,  blank=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, blank=True, null=True)
    imagem = models.ImageField(upload_to=user_directory_path)
    def __str__(self):
        return self.nome

    @staticmethod
    def get_absolute_url():
        return reverse("funcionario-list")

    @property
    def get_total_horas_extra(self):
        total = self.horaextra_set.all().aggregate(Sum('horas'))['horas__sum']
        return total or 0

gestao_rh/apps/registro_hora_extra/models.py
from django.db import models
from ..funcionario.models import Funcionario
from django.shortcuts import reverse, redirect
from django.utils.timezone import now


class HoraExtra(models.Model):
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    motivo = models.CharField(help_text="Informe o motivo", max_length=100)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    utilizadas = models.BooleanField(default=False)
    criada_em = models.DateField(default=now)

    def __str__(self):
        return self.motivo

    def get_absolute_url(self):
        return reverse('funcionario-update', args=[self.funcionario.id])

gestao_rh/apps/funcionario/api/views.py
from rest_framework import viewsets
from rest_framework.authentication import TokenAuthentication

from gestao_rh.apps.funcionario.api.serializers import FuncionarioSerializer
from gestao_rh.apps.funcionario.models import Funcionario
from rest_framework.permissions import IsAuthenticated


class FuncionarioViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    permission_classes = (IsAuthenticated,)
    authentication_classes = (TokenAuthentication,)

    queryset = Funcionario.objects.all()
    serializer_class = FuncionarioSerializer

gestao_rh/apps/funcionario/views.py
import csv
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.views import View
from django.views.generic.list import ListView
from .models import Funcionario
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy
from .tasks import send_email_app
from django.contrib.auth.models import User



def home(request):
    return HttpResponse("Funcionando")


class ListFuncionario(ListView):
    model = Funcionario
    paginate_by = 50

    def get_queryset(self):
        self.empresa = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=self.empresa)


class CreateFuncionario(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos', 'imagem']
    template_name_suffix = '_create_form'

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        funcionario.empresa = self.request.user.funcionario.empresa
        username = '-'.join(funcionario.nome.lower().split(' '))
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(CreateFuncionario, self).form_valid(form)


class UpdateFuncionario(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos', 'imagem']
    template_name_suffix = '_update_form'


class DeleteFuncionario(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('funcionario-list')


class CSVFuncionario(View):

    def get(self, request, pk):
        # Create the HttpResponse object with the appropriate CSV header.
        response = HttpResponse(content_type='text/csv')
        funcionario = get_object_or_404(Funcionario, pk=pk)
        response['Content-Disposition'] = 'attachment; filename="'+funcionario.nome+'.csv"'
        writer = csv.writer(response)
        writer.writerow([funcionario.nome, funcionario.empresa])
        for horas in funcionario.horaextra_set.all():
            writer.writerow([horas.motivo, horas.horas])
        return response


def celery(request):
    send_email_app.delay("Acelerada")
    return HttpResponse("Tarefa setada")

gestao_rh/apps/funcionario/templates/funcionario/funcionario_confirm_delete.html
{% extends "base.html" %}

{% block title %} Confirmação de Delete {% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Tem certeza que deseja apagar "{{ object }}"?</p>
    <input type="submit" value="Confirmar">
</form>
{% endblock %}

gestao_rh/apps/funcionario/templates/funcionario/funcionario_create_form.html
{% extends "base.html" %}
{% block title%}
Criar Funcionário
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Salvar">
</form>
{% endblock%}

gestao_rh/apps/funcionario/templates/funcionario/funcionario_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Lista de Funcionários
{% endblock %}

{%block content%}
<a class="btn btn-primary" href="{% url 'funcionario-create' %}">Novo</a>
<ul>

    {% for funcionario in object_list %}
        <li>
            <a href="{% url 'funcionario-update' funcionario.id %}">{{funcionario.nome}}</a>
            <div class="btn-group">
                <a class="btn btn-danger" href="{% url 'funcionario-delete' funcionario.id%}">X</a>
                <a href="{% url 'funcionario-csv' funcionario.id %}" class="btn btn-info">CSV</a>
            </div>
        </li>
    {% empty %}
        <li>Sem funcionários</li>
    {% endfor %}
    </ul>
{%endblock%}

{% block scripts_librarys %}
<script src="{% static 'js/funcionario.app.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

{% endblock %}

gestao_rh/apps/funcionario/templates/funcionario/funcionario_update_form.html
{% extends "base.html" %}
{% load bootstrap %}
{% load static %}
{% block title%}
Atualizar Funcionário
{% endblock %}

{% block content %}
<input id="funcionario_id" type="hidden" value="{{funcionario.id}}">
<form method="post">{% csrf_token %}
    {{ form | bootstrap }}
    <input class="btn btn-primary" type="submit" value="Salvar">
</form>
<a class="btn btn-warning" href="{% url 'documento-create' object.id %}">Adicionar documentos</a>
{% if object.documento_set.all|length > 0 %}
<h2>Documentos</h2>
<ul>
    {% for documento in object.documento_set.all %}
    <li><a href="{{documento.arquivo.url}}">{{documento}}</a></li>
    {% endfor %}
</ul>
{% endif %}
<br>

{% if False %}
<h2>Horas Extras</h2>
<ul>
    {% for hora_extra in object.horaextra_set.all %}
        <li><a href="{% url 'hora_extra-update' hora_extra.id %}">{{hora_extra.motivo}} - {{hora_extra.horas}}</a></li>
    {% endfor%}
    <li><b>Total</b>: {{funcionario.get_total_horas_extra}}</li>
</ul>

{% endif %}
<ul id="list_hora_extra">
</ul>
<div class="btn-group row">
    <button data-target="#hora_extra_modal" data-toggle="modal" class="btn btn-success">Adicionar Hora Extra</button>
    <a href="{% url 'pdf_funcionario_list' %}" class="btn btn-danger">Gerar Pdf</a>
</div>

<!-- Modal -->
<div class="modal fade" id="hora_extra_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="horaExtraModal">Adicionar Hora extra para {{funcionario.nome}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form>
              {% csrf_token %}
            <input id="hora_extra_valor" type="number" value="0" class="form-control" aria-label="Quantidade de horas extra">
          </form>
      </div>
      <div class="modal-footer">
        <button id="hora_extra_modal_close" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button onclick="add_hora_extra({{funcionario.id}})" type="button" class="btn btn-primary">Salvar</button>
      </div>
    </div>
  </div>
</div>
{% endblock%}


{% block scripts_librarys %}

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="{% static 'js/funcionario.app.js' %}"></script>
{% endblock %}